version: "3.9"  # optional since v1.27.0
services:
  database:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db_data:/var/lib/postgresql/data
    network_mode: host
volumes:
  db_data: